---
title: "GPA"
author: "Mason Chen"
date: "August 9, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(readr)
library(dplyr)
library(stringr)
library(purrr)
library(ggplot2)
library(lubridate)
source("../functions/clean_df_gpa.R")
```

```{r}
subject_area = read_csv("../clean_data/subject_area.csv")
names(subject_area) = c("department", "canonical_name", "subject")

gpa_data = read_csv("../clean_data/gpa_data.csv.gz")

letter_grade_data = gpa_data %>%
    filter(grade_type == "Letter Grade")

pnp_data = gpa_data %>%
    filter(grade_type == "Non-Letter Grade")

admin_code_data = gpa_data %>%
    filter(grade_type == "Administrative Code")
```

```{r}
#number of students in each department
num_students = letter_grade_data %>%
    group_by(department) %>%
    summarise(total = sum(grade_count))
average_class_size = mean(num_students$total)
average_class_size
```

```{r}
avg_gpa_data = letter_grade_data %>%
    group_by(department, year, semester) %>%
    mutate(points = grade_pts * grade_count) %>%
    summarise(gpa = sum(points)/sum(grade_count)) %>%
    ungroup() %>%
    group_by(department) %>%
    summarise(avg_gpa = mean(gpa)) %>%
    ungroup()

avg_gpa_data = inner_join(avg_gpa_data, subject_area, "department")

#plotting the gpas least to greatest
avg_gpa_plot = avg_gpa_data %>%
    ggplot(aes(avg_gpa, reorder(department, avg_gpa))) + geom_point()
avg_gpa_plot + theme_bw()

#too many departments, just going to look at the 20 highest and 20 lowest gpas
highest_gpas = avg_gpa_data %>%
    arrange(desc(avg_gpa)) %>%
    head(20)

highest_gpas %>%
    ggplot(aes(factor(department), avg_gpa)) + 
    geom_bar(stat = "identity", width = 0.5, aes(color = subject, fill = subject, alpha = 0.4)) + 
    labs(list(title = "20 Highest GPAs by Departments", x = "Average GPA", y = "Department")) +
    coord_flip() +
    scale_x_discrete(limits = rev(highest_gpas$department)) +
    scale_y_continuous(limits = c(0, 4.5), breaks = seq(0, 4.5, 0.5), expand = c(0, 0)) +
    guides(alpha = F, fill = guide_legend(title = "Subject"), color = F) +
    theme_bw()

#20 lowest gpas
lowest_gpas = avg_gpa_data %>%
    arrange((avg_gpa)) %>%
    head(20)

lowest_gpas %>%
    ggplot(aes(factor(department), avg_gpa)) + 
    geom_bar(stat = "identity", width = 0.5, aes(color = subject, fill = subject, alpha = 0.4)) + 
    labs(list(title = "20 Lowest GPAs by Departments", x = "Average GPA", y = "Department")) +
    coord_flip() +
    scale_x_discrete(limits = rev(lowest_gpas$department)) +
    scale_y_continuous(limits = c(0, 4.5), breaks = seq(0, 4.5, 0.5), expand = c(0, 0)) +
    guides(alpha = F, fill = guide_legend(title = "Subject"), color = F) + 
    theme_bw()

#average gpa data with population size
avg_gpa_class_size = inner_join(avg_gpa_data, num_students, "department")
```

```{r}
#passing rate, Satifactory/Unsatisfactory are not computed for credit
pnp_pass_rate = inner_join(pnp_data, subject_area, "department") %>%
    filter(letter_grade != "Satisfactory", letter_grade != "Unsatisfactory") %>%
    mutate(grade_pts = ifelse(letter_grade == "Pass", 1, 0)) %>%
    group_by(department, year, semester, subject) %>%
    mutate(points = grade_pts * grade_count) %>%
    summarise(gpa = sum(points)/sum(grade_count)) %>%
    ungroup() %>%
    group_by(department, subject) %>%
    summarise(avg_gpa = mean(gpa)) %>%
    ungroup()

#too many departments, just going to look at the 20 highest and 20 lowest pass rates
pnp_plot = pnp_pass_rate %>%
    ggplot(aes(avg_gpa, reorder(department, avg_gpa))) + geom_point()
pnp_plot + theme_bw()

#too many departments, just going to look at the 20 highest and 20 lowest gpas
highest_pnp = pnp_pass_rate %>%
    arrange(desc(avg_gpa)) %>%
    head(20)

highest_pnp %>%
    ggplot(aes(department, avg_gpa)) + 
    geom_bar(stat = "identity", width = 0.5, aes(color = subject, fill = subject, alpha = 0.4)) + 
    labs(list(title = "20 Highest Pass Rates by Departments", x = "Pass Percentage", y = "Department")) +
    coord_flip() +
    scale_x_discrete(limits = rev(highest_pnp$department)) +
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.15), expand = c(0, 0)) +
    guides(alpha = F, fill = guide_legend(title = "Subject"), color = F) +
    theme_bw()

#20 lowest gpas
lowest_pnp = pnp_pass_rate %>%
    arrange((avg_gpa)) %>%
    head(20)

lowest_pnp %>%
    ggplot(aes(department, avg_gpa)) + 
    geom_bar(stat = "identity", width = 0.5, aes(color = subject, fill = subject, alpha = 0.4)) + 
    labs(list(title = "20 Lowest Pass Rates by Departments", x = "Pass Percentage", y = "Department")) +
    coord_flip() +
    scale_x_discrete(limits = rev(lowest_pnp$department)) +
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.15), expand = c(0, 0)) +
    guides(alpha = F, fill = guide_legend(title = "Subject"), color = F) +
    theme_bw()
```

```{r}
#computer science gpa cap analysis

#include all cs classes
cs_gpa = letter_grade_data %>%
    filter(department == "Computer Science") %>%
    group_by(department, year, semester) %>%
    mutate(points = grade_pts * grade_count) %>%
    summarise(gpa = sum(points)/sum(grade_count)) %>%
    ungroup() %>%
    mutate(month = ifelse(semester == "fa", 9, ifelse(semester == "sp", 1, 5)), day = 1) %>%
    mutate(date = ymd(str_c(year, month, day, sep = '/'))) %>%
    arrange(date) %>%
    mutate(semester = ifelse(semester == "fa", "Fall", 
                             ifelse(semester == "sp", 
                                    "Spring", "Summer")),
           label = str_c(semester, year, sep = " "))

cs_size = letter_grade_data %>%
    filter(department == "Computer Science") %>%
    group_by(semester, year) %>%
    summarise(total = sum(grade_count)) %>%
    ungroup %>%
    mutate(semester = ifelse(semester == "fa", "Fall", 
                             ifelse(semester == "sp", 
                                    "Spring", "Summer")),
           label = str_c(semester, year, sep = " ")) %>%
    select(label, total)

cs_data = inner_join(cs_gpa, cs_size, "label")    

cs_data %>%
    ggplot(aes(date, gpa)) + 
    geom_line(color = "black") +
    geom_point(aes(size = total, color = semester)) +
    scale_x_date(breaks = cs_data$date, labels = cs_data$label) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    guides(size = F, color = guide_legend(title = "Semester")) +
    scale_color_manual(values = c("purple", "blue", "green")) +
    annotate("segment", x = ymd("2014/1/1"), xend = ymd("2014/1/1"), y = min(cs_data$gpa), yend = max(cs_data$gpa), colour = "red") +
    scale_size_area(max_size = 10) +
    labs(list(title = "GPA and Number of Students across Semesters", x = "Semester", y = "Average GPA"))
```

```{r}
#include all cs classes
cs_gpa = letter_grade_data %>%
    filter(department == "Computer Science", str_detect(course_num, "[0-9]{3,}")) %>%
    group_by(department, year, semester) %>%
    mutate(points = grade_pts * grade_count) %>%
    summarise(gpa = sum(points)/sum(grade_count)) %>%
    ungroup() %>%
    mutate(month = ifelse(semester == "fa", 9, ifelse(semester == "sp", 1, 5)), day = 1) %>%
    mutate(date = ymd(str_c(year, month, day, sep = '/'))) %>%
    arrange(date) %>%
    mutate(semester = ifelse(semester == "fa", "Fall", 
                             ifelse(semester == "sp", 
                                    "Spring", "Summer")),
           label = str_c(semester, year, sep = " "))

cs_size = letter_grade_data %>%
    filter(department == "Computer Science", str_detect(course_num, "[0-9]{3,}")) %>%
    group_by(semester, year) %>%
    summarise(total = sum(grade_count)) %>%
    ungroup %>%
    mutate(semester = ifelse(semester == "fa", "Fall", 
                             ifelse(semester == "sp", 
                                    "Spring", "Summer")),
           label = str_c(semester, year, sep = " ")) %>%
    select(label, total)

cs_data = inner_join(cs_gpa, cs_size, "label")

cs_data %>%
    ggplot(aes(date, gpa)) + 
    geom_line(color = "black") +
    geom_point(aes(size = total, color = semester)) +
    scale_x_date(breaks = cs_data$date, labels = cs_data$label) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    guides(size = F, color = guide_legend(title = "Semester")) +
    scale_color_manual(values = c("purple", "blue", "green")) +
    annotate("segment", x = ymd("2014/1/1"), xend = ymd("2014/1/1"), y = min(cs_data$gpa), yend = max(cs_data$gpa), colour = "red") +
    scale_size_area(max_size = 10) +
    labs(list(title = "GPA and Number of Students in Upper Divs\n across Semesters", x = "Semester", y = "Average GPA"))
```

```{r}
#easiest classes
easiest = letter_grade_data %>%
    group_by(department, course_num, year, semester) %>%
    mutate(points = grade_pts * grade_count) %>%
    summarise(gpa = sum(points)/sum(grade_count)) %>%
    ungroup() %>%
    group_by(department, course_num) %>%
    summarise(avg_gpa = mean(gpa)) %>%
    ungroup()
```

