---
title: "grad_time"
author: "Ian Katz"
date: "August 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)
source("../functions/summarizing_functions.R")
```

```{r}
grad_time_data <- read_csv("../clean_data/grad_time_data.csv.gz")

detailed_summarizer(grad_time_data, "time_to_grad", "gender")
summarizer(grad_time_data, "time_to_grad")
detailed_summarizer(grad_time_data, "time_to_grad", "entry_status")
# Transfer students count from the time they arrived at Berkeley,
# not total time spent in college

grad_time_by_year <- grad_time_data %>% 
  filter(entry_status == "New Freshmen",
         !is.na(time_to_grad)) %>% 
  group_by(year) %>% 
  summarise(avg = sum(count * time_to_grad) / sum(count))

ggplot(grad_time_by_year) + 
  geom_line(aes(x = year, y = avg), size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5),
                     expand = c(0, 0)) + 
  scale_y_continuous(limits = c(3, NA)) + 
  labs(title = "Time to Graduate",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  theme_bw()

grad_time_by_year
```

```{r}
grad_time_by_ethnicity <- grad_time_data %>% 
  filter(entry_status == "New Freshmen",
         !is.na(time_to_grad)) %>% 
  group_by(ethnic_category, year) %>% 
  summarise(avg = sum(count * time_to_grad) / sum(count))

ggplot(grad_time_by_ethnicity) + 
  geom_line(aes(x = year, y = avg, color = ethnic_category), size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5),
                     expand = c(0, 0)) + 
  scale_y_continuous(limits = c(3, NA)) + 
  labs(title = "Time to Graduate by Ethnicity",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  scale_color_brewer(name = "Ethnicity", type = "qual", palette = 6) + 
  theme_bw()

black_avg <- grad_time_by_ethnicity %>% 
  filter(ethnic_category == "African American")
avg_before_AA <- black_avg %>% 
  filter(year <= 1996) %>% 
  summarise(avg = mean(avg))
avg_after_AA <- black_avg %>% 
  filter(year > 1996) %>% 
  summarise(avg = mean(avg))
```


```{r}
grad_time_by_college <- grad_time_data %>% 
  filter(entry_status == "New Freshmen" &
         college != "Haas School of Business" &
         !is.na(time_to_grad) &
         !is.na(college)) %>% 
  group_by(college, year) %>% 
  summarise(avg = sum(count * time_to_grad) / sum(count))

ggplot(grad_time_by_college) + 
  geom_line(aes(x = year, y = avg, color = college), size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5),
                     expand = c(0, 0)) + 
  scale_y_continuous(limits = c(3.5, 5)) + 
  labs(title = "Time to Graduate by College",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  scale_color_brewer(name = "College", type = "qual", palette = 6) + 
  theme_bw()
```

```{r}
college_by_gender <- grad_time_data %>% 
  filter(!is.na(college)) %>% 
  group_by(year, gender, college) %>% 
  summarise(count = sum(count)) %>% 
  spread(gender, count) %>% 
  mutate(diff = Male - Female)

ggplot(college_by_gender) + 
  geom_line(aes(x = year, y = diff), size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5),
                     expand = c(0, 0)) + 
  labs(title = "Time to Graduate by College",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  scale_color_brewer(name = "College", type = "qual", palette = 6) + 
  theme_bw() + 
  facet_wrap(~college)
```


```{r}
# Interesting, but not paper worthy

grad_time_by_gender <- grad_time_data %>% 
  filter(entry_status == "New Freshmen" &
         !is.na(time_to_grad)) %>% 
  group_by(gender, year) %>% 
  summarise(avg = sum(count * time_to_grad) / sum(count))

ggplot(grad_time_by_gender) + 
  geom_line(aes(x = year, y = avg, color = gender), size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5),
                     expand = c(0, 0)) + 
  scale_y_continuous(limits = c(3.5, 5)) + 
  labs(title = "Time to Graduate by Gender",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  scale_color_brewer(name = "Gender", type = "qual", palette = 6) + 
  theme_bw()
```

```{r}
# Interesting, but not paper worthy

grad_time_by_residency <- grad_time_data %>% 
  filter(entry_status == "New Freshmen" &
         !is.na(time_to_grad)) %>% 
  group_by(residency, year) %>% 
  summarise(avg = sum(count * time_to_grad) / sum(count))

ggplot(grad_time_by_residency) + 
  geom_line(aes(x = year, y = avg, color = residency), size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5),
                     expand = c(0, 0)) + 
  scale_y_continuous(limits = c(3.5, 5)) + 
  labs(title = "Time to Graduate by Residency",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  scale_color_brewer(name = "Residency", type = "qual", palette = 6) + 
  theme_bw()
```

```{r}
# Not enough discrepency when averaged to make an interesting chart

ggplot(grad_time_by_residency) + 
  geom_bar(aes(x = residency, y = avg, filler = residency),
           stat = "identity") + 
  labs(title = "Time to Graduate by Residency",
       x = "Residency",
       y = "Average Number of Years to Graduate") + 
  scale_color_brewer(name = "Residency", type = "qual", palette = 6) + 
  theme_bw()
```


```{r}
transfer_grad_time <- grad_time_data %>% 
  filter(entry_status == "Transfers" &
         !is.na(time_to_grad)) %>% 
  group_by(year) %>% 
  summarise(avg = sum(count * time_to_grad) / sum(count))

ggplot(transfer_grad_time) + 
  geom_line(aes(x = year, y = avg), color = "red", size = 0.75) + 
  scale_x_continuous(limits = c(NA, 2008),
                     breaks = seq(1983, 2008, 5)) + 
  labs(title = "Time to Graduate for Transfers",
       x = "Year",
       y = "Average Number of Years to Graduate") + 
  theme_bw()
```

```{r}
ethnic_breakdown <- grad_time_data %>% 
  group_by(year) %>% 
  mutate(year_total = sum(count)) %>% 
  ungroup %>% 
  group_by(ethnic_category, year) %>% 
  summarise(perc = sum(count / year_total))

ggplot(ethnic_breakdown) + 
  geom_area(aes(x = year, y = perc, fill = ethnic_category)) + 
  scale_x_continuous(limits = c(NA, NA),
                     breaks = seq(1983, 2015, 8),
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 1), 
                     expand = c(0, 0)) + 
  labs(title = "Ethnic Breakdown of Students",
       x = "Year",
       y = "Percentage of Students") + 
  scale_fill_brewer(name = "Ethnicity", type = "qual", palette = 6) + 
  theme_bw()
```
